export const actionTypes = {
  SET_AUTHENTICATION: "SET_AUTHENTICATION",
  SET_ID: "SET_ID",
  SET_TOKEN: "SET_TOKEN",
  SET_ROLE: "SET_ROLE",
  SET_MOBILE: "SET_MOBILE",
  SET_CAN_DRIVE: "SET_CAN_DRIVE",
};
